version: '3.8'

services:
  trends-demo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/trends-demo
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]